### ISSUE TITLE
InGame session menu

### ISSUE THREAD

**Issue by Syopic** [Syopic/LuckyFriday#13]
Детальний опис:
https://docs.google.com/document/d/1FVGe6TxwigTCbfUh1aqNbDtHirZdc5sWtEEHpZ7I5Ic/edit#heading=h.pp0upzka3cii
Варто зауважити, що пункти меню міняються в залежності від контексту (див. опис)
Структура:
https://docs.google.com/document/d/1FVGe6TxwigTCbfUh1aqNbDtHirZdc5sWtEEHpZ7I5Ic/edit#heading=h.ooncggq4vo1c

Привязати до ESCAPE (відкрити / закрити)

**Comment by Syopic** [comment]
bug: Кнопка Restart Mission не працює

**Comment by RiksAK** [comment]
c84199823d70640ef1683b654643b71f338cbdff
Full work
