### ISSUE TITLE
GameOver screen

### ISSUE THREAD

**Issue by Syopic** [Syopic/LuckyFriday#20]
Додати екран програшу з усіма контролами згідно з https://github.com/Syopic/LuckyFriday/issues/18

**Comment by Syopic** [comment]
https://github.com/Syopic/LuckyFriday/issues/18 - документ описано - опис тут: https://docs.google.com/document/d/1FVGe6TxwigTCbfUh1aqNbDtHirZdc5sWtEEHpZ7I5Ic/edit#heading=h.a75ac2jsox2m

**Comment by RiksAK** [comment]
1d48947abaa40b602868461db0cdd261c100b58e
#18 додано UI game over як основа для творчості

**Comment by RiksAK** [comment]
e5e7ecadf730443080c12aa63e9f8637b9a8c0c6
#20 додано випадковий текст під зображенням, змінюється кнопкою "play again"
Екран програшу Game Over можна знайти по кнопці "профіль" далі з екрану "Mission Complete"
кнопка "Next"

**Comment by RiksAK** [comment]
8c3e14c6b4b1526844196351a8f7bb99b296322d
#20  додано випадковi  зображення , змінюється кнопкою "play again"
Екран програшу Game Over можна знайти по кнопці "профіль" далі з екрану "Mission Complete"
кнопка "Next"
