### ISSUE TITLE
Profile screen

### ISSUE THREAD

**Issue by Syopic** [Syopic/LuckyFriday#23]
Додати екран профілю - структура і функціонал (рейтинг і інші поля поки що забити моками) - 
Загальна структура:
https://docs.google.com/drawings/d/1JYesuoQCeYvGtHoD2T-19RojPceGhZd1FDYyD1L-OaA/edit
Макет:
https://docs.google.com/document/d/1FVGe6TxwigTCbfUh1aqNbDtHirZdc5sWtEEHpZ7I5Ic/edit#heading=h.vkkqx0pz1n0w

Дані беруться зовні з JSON-файлу assets/profile/profile.json 
https://github.com/Syopic/LuckyFriday/blob/master/assets/profile/profile.json
(його можна змінювати, якщо ця структура не влаштовує - окремо почитай по JSON - зустрічається часто і в резюме буде не зайве)
Але вантажити його треба з папки bin-debug, як рівні, тому потрібно в задачах ANT додати, аби і папка profile копіювалася разом з рівнями.

**Comment by RiksAK** [comment]
#23 8e415d29586c53d65217f0d7b45081990673e119
added UI ProfileView

**Comment by RiksAK** [comment]
full work
