### ISSUE TITLE
Нова система керування.

### ISSUE THREAD

**Issue by Hydralisk5** [Syopic/LuckyFriday#4]
Система керування основана на двох одночасних командах: 1. Напрямок руху  2.сам рух (аналог газу в авто)

Як це працює?
Гравець повинен спочатку вказати напрямок кораблю клавішами керування напрямку - далі "кермо", лише потім після натиску клавіші "газ", корабель попрямує в тому напрямку який вкаже, або точніше утримує гравець. Не відпускаючи газ, гравець може змінювати напрямок корабля. 
Крен працює сам по собі, він не впливає на рух корабля, лише крутить його навколо горизонтальної осі.

На картинкі намальовані пропоновані клавіші керування:
W, A, S, D - це клавіші які відповідають за напрямок руху(кермо). напрямки для кожної клавіші аналогічні стрілкам. W -вверх, D- вправо і т.д.
Q, E - крен корабля
О - газ 
Р - реверс - або газ назад:)
![Image of Yaktocat](https://i.gyazo.com/20d0871d911238425db69b68c036bc71.png)

Правила:
Корабель не буде рухатись, якщо зажата люба клавіша керма.
Корабель не буде рухатись, якщо зажата клавіша газу або реверсу
Корабель полетить, якщо одночасно натиснути будь-яку клавішу керма і газ
Корабель буде лише обертатися по горизонтальній осі, якщо натиснути одну із двох клавіш крену
Крен працює без клавіші газу чи реверсу.
Корабель завжди матиме низ там, де в нього нижня частина, якою він наприклад приземлюється, відповідно при любому положенні, наприклад верх ногами, напрямок руля в низ і газ, потягнуть корабель до верху. Це стосується і всіх сторін. Простими словами, всі сторони корабля відповідно керма незмінні, в якому б положенні не був корабель.

Для чого це потрібно?
Рух чи швидкість руху будь чого, людина задає як правило однією кінцівкою , одним рухом пальця, ноги тощо: автомобільний газ, газ в компютерних іграх, зокрема космолітах та авто-гонках.
Завжди легше привчити до одного руху палець який відповідатиме за газ, який можна відпустити в панічній ситуації та натиснути на реверс(тормоз в авто) та запобігти вдарянню, в яку б сторону і яким би боком не летів корабель. 

Клавіші WASD повині сприйматися гравцями як руль, або аналог хрестовини джойстиком і відчуватися майже як одне ціле, що й трапляється при грі в 3Д шутери, .

**Comment by Syopic** [comment]
done

**Comment by Syopic** [comment]
done
