### ISSUE TITLE
About popup

### ISSUE THREAD

**Issue by Syopic** [Syopic/LuckyFriday#7]
Попередньо це виглядатиме як вікно "Про програму".
Пізніше можна буде внести зміни з титрами.

Макет:
https://docs.google.com/drawings/d/1Gm8RXh8rLFr9OHTj3bEJAoDGpOzlsy5I8ZnEl7e-xtw/edit
Лого:
https://drive.google.com/open?id=0BwlVhA_cMJX9ZUpFSmtoWUU4WUE

**Comment by RiksAK** [comment]
028326bc7424f4125081e75314bff3aeae4ca2fe done
